# Generated by Django 3.1.4 on 2021-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
